"""
This file is modified from methylpy https://github.com/yupenghe/methylpy.

Author: Yupeng He

Notes added on 07/03/2022 - Difference between bismark and hisat-3n
Read mpileup doc first: http://www.htslib.org/doc/samtools-mpileup.html

For Bismark SE mapping:
Bismark converted the reads orientation based on their conversion type.
C to T conversion reads are always map to the forward strand, regardless of the R1 R2
G to A conversion reads are always map to the reverse strand, regardless of the R1 R2
Therefore, in the original bam-to-allc function, we simply consider the strandness in
the pileup format to distinguish which C needs to be counted.
There are two situations:
1. If the ref base is C, the read need to map to forward strand in order to be counted
[.ATCGN] corresponding to the forward strand
2. If the ref base is G, the read need to map to reverse strand in order to be counted
[,atcgn] corresponding to the reverse strand

For Hisat-3n PE or Biskarp PE mapping:
R1 R2 are mapped as their original orientation, therefore,
both the C to T and G to A conversion reads can have forward and reverse strand alignment.
We can not distinguish the conversion type by strand in input bam.
Here I add a check using the YZ tag of hisat-3n BAM file or XG tag of bismark BAM file.
If the YZ tag is "+" or XG tag is "CT", the read is C to T conversion, I change the flag to forward mapping
no matter R1 or R2 by read.is_forward = True
If the YZ tag is "-" or XG tag is "GA", the read is G to A conversion, I change the flag to reverse mapping
no matter R1 or R2 by read.is_forward = False
In this case, the read orientation is the same as bismark bam file, and the following base
count code no need to change.

"""

import collections
import logging
import pathlib
import shlex
import subprocess
from concurrent.futures import ProcessPoolExecutor, as_completed

import pandas as pd
import pysam

from ._doc import *
from ._open import open_allc, open_bam
from .utilities import genome_region_chunks

# logger
log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())


def _is_read_ct_conversion_hisat3n(read):
    return read.get_tag("YZ") == "+"


def _is_read_ct_conversion_bismark(read):
    return read.get_tag("XG") == "CT"


def _convert_bam_strandness(in_bam_path, out_bam_path):
    with pysam.AlignmentFile(in_bam_path) as in_bam, pysam.AlignmentFile(
        out_bam_path, header=in_bam.header, mode="wb"
    ) as out_bam:
        is_ct_func = None
        for read in in_bam:
            if is_ct_func is None:
                if read.has_tag("YZ"):
                    is_ct_func = _is_read_ct_conversion_hisat3n
                elif read.has_tag("XG"):
                    is_ct_func = _is_read_ct_conversion_bismark
                else:
                    raise ValueError(
                        "The bam file reads has no conversion type tag "
                        "(XG by bismark or YZ by hisat-3n). Please note that this function can "
                        "only process bam files generated by bismark or hisat-3n."
                    )
            if is_ct_func(read):
                read.is_forward = True
                if read.is_paired:
                    read.mate_is_forward = True
            else:
                read.is_forward = False
                if read.is_paired:
                    read.mate_is_forward = False
            out_bam.write(read)
    return


def _read_faidx(faidx_path):
    """
    Read fadix of reference fasta file.

    samtools fadix ref.fa
    """
    return pd.read_csv(
        faidx_path,
        index_col=0,
        header=None,
        sep="\t",
        names=["NAME", "LENGTH", "OFFSET", "LINEBASES", "LINEWIDTH"],
    )


def _get_chromosome_sequence_upper(fasta_path, fai_df, query_chrom):
    """Read a whole chromosome sequence into memory."""
    chrom_pointer = fai_df.loc[query_chrom, "OFFSET"]
    tail = fai_df.loc[query_chrom, "LINEBASES"] - fai_df.loc[query_chrom, "LINEWIDTH"]
    seq = ""
    with open(fasta_path) as f:
        f.seek(chrom_pointer)
        for line in f:
            if line[0] == ">":
                break
            seq += line[:tail]  # trim \n
    return seq.upper()


def _get_bam_chrom_index(bam_path):
    result = subprocess.run(["samtools", "idxstats", bam_path], stdout=subprocess.PIPE, encoding="utf8").stdout

    chrom_set = set()
    for line in result.split("\n"):
        chrom = line.split("\t")[0]
        if chrom not in ["", "*"]:
            chrom_set.add(chrom)
    return pd.Index(chrom_set)


def hamming_distance(str1, str2):
    """Calculate hamming distance between two strings."""
    if len(str1) != len(str2):
        raise ValueError("Strings must be of equal length.")
    return sum(ch1 != ch2 for ch1, ch2 in zip(str1, str2))


def correct_tag(mpileup_line, ref_base):
    """Correct UMI in mpileup output - optimized version.
    Input will like:
    chr1    46930353        C       1       ,       I       GAAGGTGTGTAT
    chr1    46930354        C       1       ,       I       GAAGGTGTGTAT
    chr1    47151364        C       1       T     I       TTATATGGGGAG
    chr1    47791302        C       2       TT      II      TGGTTGAGTGTG,GTAGTGTTTGAG
    ...
    column 1 is chromosome
    column 2 is position
    column 3 is reference base
    column 4 is read depth
    column 5 is base sequence
    column 6 is base quality
    column 7 is UMI, separated by comma
    """
    mpileup_fields = mpileup_line.strip().split("\t")
    
    # Check if we have enough fields
    if len(mpileup_fields) < 7:
        return mpileup_line, 0, 0
    
    # when ref base is C, just extract seq is . or T pos info
    # when ref base is G, just extract seq is , or a pos info
    seqs = mpileup_fields[4]  # Keep as string for faster operations
    if ref_base == "C":
        valid_chars = {".", "T"}
    elif ref_base == "G":
        valid_chars = {",", "a"}
    else:
        return mpileup_line, 0, 0  # Skip if not C or G
    
    # Find valid positions using list comprehension for better performance
    keep_indices = [i for i, char in enumerate(seqs) if char in valid_chars]
    cov_raw = len(keep_indices)
    
    # If no valid positions found, return empty result
    if not keep_indices:
        mpileup_fields[3] = "0"  # Set coverage to 0
        mpileup_fields[4] = ""   # Empty sequence
        mpileup_fields[5] = ""   # Empty quality
        mpileup_fields[-1] = "" # Empty UMI
        return "\t".join(mpileup_fields), 0, 0
    
    # The last field records UMIs, each UMI is separated by comma
    umis = mpileup_fields[-1].split(",")
    quals = mpileup_fields[5]  # Keep as string
    
    # Check length consistency before UMI correction
    if len(seqs) != len(quals) or len(seqs) != len(umis):
        log.warning(f"Length mismatch at {mpileup_fields[0]}:{mpileup_fields[1]} - "
                   f"seqs: {len(seqs)}, quals: {len(quals)}, umis: {len(umis)}. "
                   f"Skipping UMI correction for this position.")
        return mpileup_line, 0, 0  # Return original if inconsistent
    
    # Filter using indices - more efficient than multiple list comprehensions
    filtered_umis = [umis[i] for i in keep_indices]
    filtered_quals = [quals[i] for i in keep_indices]
    filtered_seqs = [seqs[i] for i in keep_indices]
    
    # Count UMIs using Counter for efficiency
    umi_count = collections.Counter(filtered_umis)
    
    # Group data by UMI more efficiently
    umi_dict = {}
    for i, umi in enumerate(filtered_umis):
        if umi not in umi_dict:
            umi_dict[umi] = {"qual": [], "seq": []}
        umi_dict[umi]["qual"].append(filtered_quals[i])
        umi_dict[umi]["seq"].append(filtered_seqs[i])
    
    # UMI correction: merge UMIs with hamming distance of 1
    unique_umis = list(umi_dict.keys())
    
    i = 0
    while i < len(unique_umis):
        umi1 = unique_umis[i]
        if umi1 not in umi_dict:  # Already merged
            i += 1
            continue
            
        j = i + 1
        while j < len(unique_umis):
            umi2 = unique_umis[j]
            if umi2 not in umi_dict:  # Already merged
                j += 1
                continue
            
            if len(umi1) == len(umi2):
                try:
                    if hamming_distance(umi1, umi2) == 1:
                        if umi_count[umi1] > umi_count[umi2]:
                            # Merge umi2 into umi1
                            umi_dict[umi1]["qual"].extend(umi_dict[umi2]["qual"])
                            umi_dict[umi1]["seq"].extend(umi_dict[umi2]["seq"])
                            del umi_dict[umi2]
                        elif umi_count[umi1] < umi_count[umi2]:
                            # Merge umi1 into umi2
                            umi_dict[umi2]["qual"].extend(umi_dict[umi1]["qual"])
                            umi_dict[umi2]["seq"].extend(umi_dict[umi1]["seq"])
                            del umi_dict[umi1]
                            break
                        # If counts are equal, keep both UMIs separate
                except ValueError:
                    pass  
            j += 1
        i += 1
    
    # Base correction for each UMI
    for umi, info in umi_dict.items():
        seq_counts = collections.Counter(info["seq"])
        if len(seq_counts) > 1:
            # Get the most common base and its count
            most_common_bases = seq_counts.most_common()
            most_common_base, most_common_count = most_common_bases[0]
            
            # Check if there's a tie for the most common base
            tied_bases = [base for base, count in most_common_bases if count == most_common_count]
            
            if len(tied_bases) == 1:
                # Clear winner by count, use the most common base
                corrected_base = most_common_base
            else:
                # Tie in counts, decide by quality scores
                base_quality_map = {}
                for seq, qual in zip(info["seq"], info["qual"]):
                    if seq in tied_bases:
                        if seq not in base_quality_map:
                            base_quality_map[seq] = []
                        base_quality_map[seq].append(ord(qual) - 33) 
                
                # Calculate average quality for each tied base
                best_base = most_common_base  # Default fallback
                best_avg_quality = -1
                for base, qualities in base_quality_map.items():
                    avg_quality = sum(qualities) / len(qualities)
                    if avg_quality > best_avg_quality:
                        best_avg_quality = avg_quality
                        best_base = base
                
                corrected_base = best_base
            
            # Apply correction: replace all bases with the corrected base
            info["seq"] = [corrected_base] * len(info["seq"])
    
    # Reassemble mpileup fields
    if not umi_dict:
        # No valid UMIs left
        mpileup_fields[3] = "0"
        mpileup_fields[4] = ""
        mpileup_fields[5] = ""
        mpileup_fields[-1] = ""
    else:
        # Update coverage count
        mpileup_fields[3] = str(len(umi_dict))
        # Use join for better performance than string concatenation
        umi_keys = list(umi_dict.keys())
        mpileup_fields[-1] = ",".join(umi_keys)
        mpileup_fields[4] = "".join(umi_dict[umi]["seq"][0] for umi in umi_keys)
        mpileup_fields[5] = "".join(umi_dict[umi]["qual"][0] for umi in umi_keys)
    cov_new = len(umi_dict)
    return "\t".join(mpileup_fields), cov_raw, cov_new

def _bam_to_allc_worker(
    bam_path,
    reference_fasta,
    fai_df,
    output_path,
    region=None,
    num_upstr_bases=0,
    num_downstr_bases=2,
    buffer_line_number=100000,
    min_mapq=0,
    min_base_quality=1,
    compress_level=5,
    tabix=True,
    save_count_df=False,
    tag=None,
    debug=False,
):
    """None parallel bam_to_allc worker function, call by bam_to_allc."""
    # mpileup
    mpileup_params = ""
    mpileup_fix_output_param = "--no-output-ins-mods --no-output-ins --no-output-ins --no-output-del --no-output-del --no-output-ends "
    if tag:
        mpileup_params = f" --output-extra {tag} "
    if region is None:
        mpileup_cmd = (
            f"samtools mpileup -Q {min_base_quality} -q {min_mapq} -B "
            f"-f {reference_fasta}{mpileup_params} {mpileup_fix_output_param} {bam_path}"
        )
        pipes = subprocess.Popen(
            shlex.split(mpileup_cmd),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        )
    else:
        bam_handle = open_bam(
            bam_path,
            region=region,
            mode="r",
            include_header=True,
            samtools_parms_str=None,
        )
        mpileup_cmd = (
            f"samtools mpileup -Q {min_base_quality} -q {min_mapq} -B "
            f"-f {reference_fasta}{mpileup_params} {mpileup_fix_output_param} -"
        )
        pipes = subprocess.Popen(
            shlex.split(mpileup_cmd),
            stdin=bam_handle.file,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        )

    result_handle = pipes.stdout

    output_file_handler = open_allc(output_path, mode="w", compresslevel=compress_level)

    # initialize variables
    complement = {"A": "T", "T": "A", "C": "G", "G": "C", "N": "N"}
    mc_sites = {"C", "G"}
    context_len = num_upstr_bases + 1 + num_downstr_bases
    cur_chrom = ""
    line_counts = 0
    total_line = 0
    out = ""
    seq = None  # whole cur_chrom seq
    chr_out_pos_list = []
    cur_out_pos = 0
    cov_dict = collections.defaultdict(int)  # context: cov_total
    mc_dict = collections.defaultdict(int)  # context: mc_total
    num_dict = collections.defaultdict(int)  # context: context_number
    if debug:
        mpl_fh1 = open(f"{output_path.replace('.gz','')}_mpl_old.txt", "w")
        mpl_fh2 = open(f"{output_path.replace('.gz','')}_mpl_correction.txt", "w")
    # process mpileup result
    total_cov_raw = 0
    total_cov_new = 0
    for line in result_handle:
        total_line += 1
        fields = line.strip().split("\t")
        fields[2] = fields[2].upper()
        # if chrom changed, read whole chrom seq from fasta
        if fields[0] != cur_chrom:
            cur_chrom = fields[0]
            chr_out_pos_list.append((cur_chrom, str(cur_out_pos)))
            # get seq for cur_chrom
            seq = _get_chromosome_sequence_upper(reference_fasta, fai_df, cur_chrom)

        if fields[2] not in mc_sites:
            continue
        
        # Now we use --no-output-ins --no-output-ins --no-output-del --no-output-del to remove indel reads info
        '''
        # deal with indels
        read_bases = fields[4]
        if "+" in read_bases or "-" in read_bases:
            quals = fields[5] if len(fields) > 5 else ""
            umis = fields[6].split(",") if len(fields) > 6 else []
            keep_quals = []
            keep_umis = []
            read_bases_list = []
            
            i = 0
            base_idx = 0  # Track actual base position for quals/umis alignment
            
            while i < len(read_bases):
                char = read_bases[i]
                if char in "+-":
                    # Skip indel notation - find the number and skip that many characters
                    i += 1
                    if i < len(read_bases) and read_bases[i].isdigit():
                        # Extract the full number (could be multi-digit)
                        num_str = ""
                        while i < len(read_bases) and read_bases[i].isdigit():
                            num_str += read_bases[i]
                            i += 1
                        # Skip the indel sequence
                        indel_len = int(num_str)
                        i += indel_len
                    
                else:
                    # Keep this base and its corresponding qual/umi
                    read_bases_list.append(char)
                    if base_idx < len(quals):
                        keep_quals.append(quals[base_idx])
                    if base_idx < len(umis):
                        keep_umis.append(umis[base_idx])
                    base_idx += 1
                    i += 1
            
            # Update fields efficiently
            fields[4] = "".join(read_bases_list)
            fields[5] = "".join(keep_quals)
            fields[6] = ",".join(keep_umis)
        '''
        # count converted and unconverted bases
        if fields[2] == "C":
            if debug and mpl_fh1:
                mpl_fh1.write(line)
            # mpileup pos is 1-based, turn into 0 based
            pos = int(fields[1]) - 1
            try:
                context = seq[(pos - num_upstr_bases) : (pos + num_downstr_bases + 1)]
            except Exception:  # complete context is not available, skip
                continue
            if tag:
                new_line, cov_raw, cov_new = correct_tag("\t".join(fields), "C")
                fields = new_line.split("\t")
                total_cov_raw += int(cov_raw)
                total_cov_new += int(cov_new)
                if debug and mpl_fh2:
                    mpl_fh2.write(f"{new_line}\n")
            # Only count . and T, discard reads containing sequencing errors
            unconverted_c = fields[4].count(".")
            converted_c = fields[4].count("T")
            cov = unconverted_c + converted_c
            if cov > 0 and len(context) == context_len:
                line_counts += 1
                data = (
                    "\t".join(
                        [
                            cur_chrom,
                            str(pos + 1),
                            "+",
                            context,
                            str(unconverted_c),
                            str(cov),
                            "1",
                        ]
                    )
                    + "\n"
                )
                cov_dict[context] += cov
                mc_dict[context] += unconverted_c
                num_dict[context] += 1
                out += data
                cur_out_pos += len(data)

        elif fields[2] == "G":
            if debug and mpl_fh1:
                mpl_fh1.write(line)
            pos = int(fields[1]) - 1
            try:
                context = "".join(
                    [
                        complement[base]
                        for base in reversed(seq[(pos - num_downstr_bases) : (pos + num_upstr_bases + 1)])
                    ]
                )
            except Exception:  # complete context is not available, skip
                continue
            if tag:
                new_line, cov_raw, cov_new = correct_tag("\t".join(fields), "G")
                fields = new_line.split("\t")
                total_cov_raw += int(cov_raw)
                total_cov_new += int(cov_new)
                if debug and mpl_fh2:
                    mpl_fh2.write(f"{new_line}\n")
            unconverted_c = fields[4].count(",")
            converted_c = fields[4].count("a")
            cov = unconverted_c + converted_c
            if cov > 0 and len(context) == context_len:
                line_counts += 1
                data = (
                    "\t".join(
                        [
                            cur_chrom,
                            str(pos + 1),  # ALLC pos is 1-based
                            "-",
                            context,
                            str(unconverted_c),
                            str(cov),
                            "1",
                        ]
                    )
                    + "\n"
                )
                cov_dict[context] += cov
                mc_dict[context] += unconverted_c
                num_dict[context] += 1
                out += data
                cur_out_pos += len(data)

        if line_counts > buffer_line_number:
            output_file_handler.write(out)
            line_counts = 0
            out = ""

    if line_counts > 0:
        output_file_handler.write(out)
    result_handle.close()
    output_file_handler.close()
    if debug:
        mpl_fh1.close()
        mpl_fh2.close()

    if tabix:
        subprocess.run(shlex.split(f"tabix -b 2 -e 2 -s 1 {output_path}"), check=True)

    count_df = pd.DataFrame({"mc": mc_dict, "cov": cov_dict, "number": num_dict})
    count_df["mc_rate"] = count_df["mc"] / count_df["cov"]

    total_genome_length = fai_df["LENGTH"].sum()
    count_df["genome_cov"] = total_line / total_genome_length
    if total_cov_raw > 0:
        count_df["genome_cov_raw_umi"] = total_cov_raw
        count_df["cell_saturation"] = 1- (total_cov_new / total_cov_raw)
    if total_cov_new > 0:
        count_df["genome_cov_new_umi"] = total_cov_new

    if save_count_df:
        count_df.to_csv(output_path + ".count.csv")
        return None
    else:
        return count_df


def _aggregate_count_df(count_dfs):
    total_df = pd.concat(count_dfs)
    total_df = total_df.groupby(total_df.index).sum()
    total_df["mc_rate"] = total_df["mc"] / total_df["cov"]
    total_df["mc"] = total_df["mc"].astype(int)
    total_df["cov"] = total_df["cov"].astype(int)
    return total_df


@doc_params(
    compress_level_doc=compress_level_doc,
    cpu_basic_doc=cpu_basic_doc,
    reference_fasta_doc=reference_fasta_doc,
    convert_bam_strandness_doc=convert_bam_strandness_doc,
)
def bam_to_allc(
    bam_path,
    reference_fasta,
    output_path=None,
    cpu=1,
    num_upstr_bases=0,
    num_downstr_bases=2,
    min_mapq=10,
    min_base_quality=20,
    compress_level=5,
    save_count_df=False,
    convert_bam_strandness=False,
    tag=None,
    debug=False,
):
    """\
    Generate 1 ALLC file from 1 position sorted BAM file via samtools mpileup.

    Parameters
    ----------
    bam_path
        Path to 1 position sorted BAM file
    reference_fasta
        {reference_fasta_doc}
    output_path
        Path to 1 output ALLC file
    cpu
        {cpu_basic_doc} DO NOT use cpu > 1 for single cell ALLC generation.
        Parallel on cell level is better for single cell project.
    num_upstr_bases
        Number of upstream base(s) of the C base to include in ALLC context column,
        usually use 0 for normal BS-seq, 1 for NOMe-seq.
    num_downstr_bases
        Number of downstream base(s) of the C base to include in ALLC context column,
        usually use 2 for both BS-seq and NOMe-seq.
    min_mapq
        Minimum MAPQ for a read being considered, samtools mpileup parameter, see samtools documentation.
    min_base_quality
        Minimum base quality for a base being considered, samtools mpileup parameter,
        see samtools documentation.
    compress_level
        {compress_level_doc}
    save_count_df
        If true, save an ALLC context count table next to ALLC file.
    convert_bam_strandness
        {convert_bam_strandness_doc}
    tag
        Tag name to extract from BAM file using samtools mpileup --output-extra.
        Common tags include: 'UR' for raw UMI sequences, 'UB' for corrected UMI sequences,
        'CB' for cell barcodes. When specified, the tag values will be included in the
        mpileup output and can be used for UMI-based error correction. For example,
        using 'UR' will enable UMI correction with 1 edit distance tolerance.
    debug
        If True, output debug files (mpl_fh1 and mpl_fh2) containing mpileup information.
        Default is False.

    Returns
    -------
    count_df
        a pandas.DataFrame for overall mC and cov count separated by mC context.
    """
    buffer_line_number = 100000
    tabix = True

    # Check fasta index
    if not pathlib.Path(reference_fasta).exists():
        raise FileNotFoundError(f"Reference fasta not found at {reference_fasta}.")
    if not pathlib.Path(reference_fasta + ".fai").exists():
        raise FileNotFoundError("Reference fasta not indexed. Use samtools faidx to index it and run again.")
    fai_df = _read_faidx(pathlib.Path(reference_fasta + ".fai"))

    if convert_bam_strandness:
        temp_bam_path = f"{output_path}.temp.bam"
        _convert_bam_strandness(bam_path, temp_bam_path)
        bam_path = temp_bam_path

    if not pathlib.Path(bam_path + ".bai").exists():
        subprocess.check_call(shlex.split("samtools index " + bam_path))

    # check chromosome between BAM and FASTA
    # samtools have a bug when chromosome not match...
    bam_chroms_index = _get_bam_chrom_index(bam_path)
    unknown_chroms = [i for i in bam_chroms_index if i not in fai_df.index]
    if len(unknown_chroms) != 0:
        unknown_chroms = " ".join(unknown_chroms)
        raise IndexError(
            f"BAM file contain unknown chromosomes: {unknown_chroms}\n"
            "Make sure you use the same genome FASTA file for mapping and bam-to-allc."
        )

    # if parallel, chunk genome
    if cpu > 1:
        regions = genome_region_chunks(reference_fasta + ".fai", bin_length=100000000, combine_small=False)
    else:
        regions = None

    # Output path
    input_path = pathlib.Path(bam_path)
    file_dir = input_path.parent
    if output_path is None:
        allc_name = "allc_" + input_path.name.split(".")[0] + ".tsv.gz"
        output_path = str(file_dir / allc_name)
    else:
        if not output_path.endswith(".gz"):
            output_path += ".gz"

    if cpu > 1:
        raise NotImplementedError

        temp_out_paths = []
        for batch_id in range(len(regions)):
            temp_out_paths.append(output_path + f".batch_{batch_id}.tmp.tsv.gz")

        with ProcessPoolExecutor(max_workers=cpu) as executor:
            future_dict = {}
            for batch_id, (region, out_temp_path) in enumerate(zip(regions, temp_out_paths)):
                _kwargs = {
                    "bam_path": bam_path,
                    "reference_fasta": reference_fasta,
                    "fai_df": fai_df,
                    "output_path": out_temp_path,
                    "region": region,
                    "num_upstr_bases": num_upstr_bases,
                    "num_downstr_bases": num_downstr_bases,
                    "buffer_line_number": buffer_line_number,
                    "min_mapq": min_mapq,
                    "min_base_quality": min_base_quality,
                    "compress_level": compress_level,
                    "tabix": False,
                    "save_count_df": False,
                    "tag": tag,
                    "debug": debug,
                }
                future_dict[executor.submit(_bam_to_allc_worker, **_kwargs)] = batch_id

            count_dfs = []
            for future in as_completed(future_dict):
                batch_id = future_dict[future]
                try:
                    count_dfs.append(future.result())
                except Exception as exc:
                    log.info(f"{batch_id!r} generated an exception: {exc}")

            # aggregate ALLC
            with open_allc(
                output_path,
                mode="w",
                compresslevel=compress_level,
                threads=1,
                region=None,
            ) as out_f:
                # TODO: Parallel ALLC is overlapped,
                #  the split by region strategy only split reads, but reads can overlap
                # need to adjust and merge end rows in aggregate ALLC
                for out_temp_path in temp_out_paths:
                    with open_allc(out_temp_path) as f:
                        for line in f:
                            out_f.write(line)
                    subprocess.check_call(["rm", "-f", out_temp_path])

            # tabix
            if tabix:
                subprocess.run(shlex.split(f"tabix -b 2 -e 2 -s 1 {output_path}"), check=True)

            # aggregate count_df
            count_df = _aggregate_count_df(count_dfs)
            if save_count_df:
                count_df.to_csv(output_path + ".count.csv")

            # clean up temp bam
            if convert_bam_strandness:
                # this bam path is the temp file path
                subprocess.check_call(["rm", "-f", bam_path])
                subprocess.check_call(["rm", "-f", f"{bam_path}.bai"])
            return count_df
    else:
        result = _bam_to_allc_worker(
            bam_path,
            reference_fasta,
            fai_df,
            output_path,
            region=None,
            num_upstr_bases=num_upstr_bases,
            num_downstr_bases=num_downstr_bases,
            buffer_line_number=buffer_line_number,
            min_mapq=min_mapq,
            min_base_quality=min_base_quality,
            compress_level=compress_level,
            tabix=tabix,
            save_count_df=save_count_df,
            tag=tag,
            debug=debug
        )

        # clean up temp bam
        if convert_bam_strandness:
            # this bam path is the temp file path
            subprocess.check_call(["rm", "-f", bam_path])
            subprocess.check_call(["rm", "-f", f"{bam_path}.bai"])

        return result
